default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://postgres@localhost:5432') %>

development:
  <<: *default
  database: govuk_mockup_kit_development

test:
  <<: *default
  database: govuk_mockup_kit_test

production:
  <<: *default
  database: govuk_mockup_kit_production
